angular.module("directives",[])
    .directive("menu",function(){
        return {
            restrict:"ECMA",//4种方式出现（元素、类名、注释、属性）
            //template:"<div>div</div>"
            templateUrl:"demo.html",
            //replace:true,//真正的替换（替换的内容为一个跟标签）
            transclude:true,//替换但保留原有的内容
            scope:{},//每个指令是独立的值为(false、true、@、=、&、{})
            link:function($scope,b,c){
                $scope.data=[
                    {
                        name:"111",
                        son:[
                            {name:"1-1"},
                            {name:"1-2"},
                            {name:"1-3"},
                            {name:"1-4"}
                        ]
                    },
                    {
                        name:"222",
                        son:[
                            {name:"2-1"},
                            {name:"2-2"},
                            {name:"2-3"},
                            {name:"2-4"}
                        ]
                    },
                    {
                        name:"333",
                        son:[
                            {name:"3-1"},
                            {name:"3-2"},
                            {name:"3-3"},
                            {name:"3-4"}
                        ]
                    },
                ];
                $scope.a=0;
                $scope.change=function(id){
                    //alert(1);
                    $scope.a=id;
                }
            }
        }
    }).controller("ctrl",function($scope){
    $scope.abc="我是控制器上的值"
})